// Generated by CoffeeScript 1.6.3
Meteor.startup(function() {
  Meteor.autorun(function() {
    document.title = Session.get('title');
  });
});

Session.set("title", "Complimentary Mintz");

Session.set('entering', true);

Session.set('entering-errors', false);

console.log(moment().format());
